# .prettierrc.yml
# Prettier configuration for TypeScript Node.js VSCode Extension Development

# Specify the line length that the printer will wrap on.
printWidth: 80

# Specify the number of spaces per indentation level.
tabWidth: 2

# Indent lines with spaces, not tabs.
useTabs: false

# Print semicolons at the ends of statements.
semi: true

# Use single quotes instead of double quotes.
singleQuote: true

# Use single quotes in JSX.
jsxSingleQuote: false

# Print trailing commas wherever possible when multi-line.
trailingComma: "all"

# Print spaces between brackets in object literals.
bracketSpacing: true

# Include parentheses around a sole arrow function parameter.
arrowParens: "always"

# Put the > of a multi-line JSX element at the end of the last line instead of being alone on the next line.
jsxBracketSameLine: false

# Format only the beginning and end of the file to avoid unnecessary formatting.
rangeStart: 0

# Specify which parser to use.
parser: "typescript"

# Do not format code using these file extensions.
excludeFiles: ["*.min.js", "bundle.js"]

endOfLine: auto

# Override settings for specific file types.
overrides:
  - files: "*.json"
    options:
      tabWidth: 2
  - files: "*.yml"
    options:
      tabWidth: 2
