branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/npm"
  - "@semantic-release/github"
  - "@semantic-release/git"
    with:
      assets:
        - "CHANGELOG.md"
      message: "chore(release): set `package.json` to %%nextRelease.version%% [skip ci]\n\n%%nextRelease.notes%%"